### ISSUE TITLE
make failes on error: cannot install, GOBIN must be an absolute path

### ISSUE THREAD

**Issue by RamLavi** [qinqon/kube-admission-webhook#1]
hack/install-go.sh 1.12.15
++ grep '^go ' go.mod
++ awk '{print $2}'
+ version=1.12.15
+ unset GOFLAGS
+ go get golang.org/dl/go1.12.15
go: finding golang.org/dl/go1.12.15 latest
go: finding golang.org/dl latest
cannot install, GOBIN must be an absolute path
make: *** [Makefile:15: /home/ralavi/go/bin/go1.12.15] Error 1

**Comment by qinqon** [comment]
Thi sis my crazy approach, I am going for knmstate approach of just using tarball

**Comment by qinqon** [comment]
I have re-wrote it, I am going to close the issue.
