### ISSUE TITLE
After rotation traffic is rejected until pod volume is updated

### ISSUE THREAD

**Issue by qinqon** [qinqon/kube-admission-webhook#12]
**Describe the bug**
When rotation is done the caBundle and service Secret is update but it takes some time for the pod volume to be updated, at kubevirtci it's around 1 minute.

**To Reproduce**

**Expected behavior**
This has to be done same way as openshift.
```
we rotate properly, which means we expand trust first, everything gets some time to trust the new CA bundle and still trusts the old serving certs, then the secrets are all updated to be signed by the new signer. Later, the trust is tightened to remove the old cert, after it expires
```
https://github.com/openshift/enhancements/blob/master/enhancements/authentication/automated-service-ca-rotation.md

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by phoracek** [comment]
@qinqon I think you have a bad template for your Issues... :D

**Comment by qinqon** [comment]
@phoracek there is a solution for this, looks like we can have more than one CA at caBundle, so we can do a transition.
